# Generated by Django 5.0.1 on 2024-02-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
